import { ArrowLeft, ArrowRight, BedDouble, CalendarDays, Check, Heart, MapPin, MessageCircle, Navigation, Plane, ShieldCheck, ShoppingBag, Star, Utensils, Wallet } from "lucide-react";
import { useEffect, useState, type ReactNode, type SyntheticEvent } from "react";
import { Link, useNavigate, useParams } from "react-router-dom";
import { destinations, formatINR, getDestinationGuide, getReviewsForDestination, getShopsForDestination, getStaysForDestination, places, restaurants, stays, type Destination } from "../data/catalog";
import { useVoyara } from "../context/VoyaraContext";

const imageFallback = "data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 1200 800'%3E%3Cdefs%3E%3ClinearGradient id='g' x1='0' y1='0' x2='1' y2='1'%3E%3Cstop stop-color='%23183927'/%3E%3Cstop offset='1' stop-color='%234a8558'/%3E%3C/linearGradient%3E%3C/defs%3E%3Crect width='1200' height='800' fill='url(%23g)'/%3E%3Cpath d='M0 610 260 360l150 150 200-250 210 260 160-170 220 260v190H0Z' fill='%23d8fbcc' fill-opacity='.38'/%3E%3Ccircle cx='940' cy='170' r='72' fill='%23fff4c7' fill-opacity='.8'/%3E%3C/svg%3E";

function useImageFallback(event: SyntheticEvent<HTMLImageElement>) {
  event.currentTarget.onerror = null;
  event.currentTarget.src = imageFallback;
}

function placeAsDestination(place: (typeof places)[number]): Destination {
  return { id: place.id, name: place.name, country: place.country, region: place.state, category: place.type, rating: place.rating, places: 1, fromPrice: 6500, bestTime: "Check seasonal conditions", description: place.description, image: place.image, thingsToDo: [place.name] };
}

export default function DestinationDetails() {
  const { id } = useParams();
  const navigate = useNavigate();
  const { favorites, toggleFavorite } = useVoyara();
  const directDestination = destinations.find((item) => item.id === id);
  const selectedPlace = directDestination ? undefined : places.find((item) => item.id === id);
  const destination = directDestination ?? destinations.find((item) => item.id === selectedPlace?.destinationId) ?? (selectedPlace ? placeAsDestination(selectedPlace) : undefined);
  const [selectedImage, setSelectedImage] = useState("");

  useEffect(() => {
    setSelectedImage(destination?.image ?? "");
  }, [destination?.id, destination?.image]);

  if (!destination) {
    return <main className="grid min-h-[65vh] place-items-center bg-[#fbfaf7] px-5 text-center"><div><h1 className="text-3xl font-black">Place not found</h1><p className="mt-2 text-slate-500">Choose a destination or local place from the current travel catalogue.</p><Link to="/destinations" className="mt-6 inline-flex rounded-full bg-[#183927] px-5 py-3 text-sm font-bold text-white">Browse destinations</Link></div></main>;
  }

  const saved = favorites.some((item) => item.kind === "destination" && item.id === destination.id);
  const localPlaces = places.filter((item) => item.destinationId === destination.id);
  const localRestaurants = restaurants.filter((item) => item.destinationId === destination.id);
  const stayOptions = getStaysForDestination(destination);
  const guide = getDestinationGuide(destination);
  const shopping = getShopsForDestination(destination);
  const reviews = getReviewsForDestination(destination);
  const gallery = [...new Set(destination.gallery?.length ? destination.gallery : [destination.image, ...localPlaces.map((place) => place.image)])].filter(Boolean).slice(0, 3);
  const thingsToDo = destination.thingsToDo?.length ? destination.thingsToDo : localPlaces.map((item) => item.name);
  const foods = destination.foods?.length ? destination.foods : localRestaurants.map((item) => item.cuisine);
  const tips = destination.travelTips?.length ? destination.travelTips : ["Check local opening hours and weather before setting out.", "Use registered operators for paid activities.", "Keep a little time free for local recommendations."];
  const averageReview = (reviews.reduce((total, review) => total + review.rating, 0) / reviews.length).toFixed(1);

  return <main className="min-h-screen bg-[#fbfaf7] pb-16">
    <section className="mx-auto max-w-7xl px-5 pt-7 sm:px-8 lg:px-10">
      <button type="button" onClick={() => navigate(-1)} className="inline-flex items-center gap-2 text-sm font-bold text-slate-600 hover:text-slate-950"><ArrowLeft size={17} /> Back to results</button>
      <div className="mt-6 grid gap-4 lg:grid-cols-[1.5fr_.5fr]">
        <div className="relative h-[340px] overflow-hidden rounded-[2rem] bg-[#183927] sm:h-[480px]"><img src={selectedImage || destination.image} onError={useImageFallback} alt={destination.name} className="h-full w-full object-cover" /><div className="absolute inset-x-0 bottom-0 bg-gradient-to-t from-black/75 via-black/20 to-transparent px-6 pb-6 pt-24 text-white"><p className="text-xs font-bold uppercase tracking-[.2em] text-white/75">{destination.category} guide</p><h1 className="mt-2 text-4xl font-black tracking-[-.05em] sm:text-6xl">{destination.name}</h1><p className="mt-2 flex items-center gap-1.5 text-sm text-white/85"><MapPin size={16} /> {destination.region}, {destination.country}</p></div></div>
        <div className="grid grid-cols-2 gap-4 lg:grid-cols-1">{gallery.slice(1, 3).map((image) => <button key={image} type="button" onClick={() => setSelectedImage(image)} aria-label={`Show another ${destination.name} photo`} className={`min-h-36 overflow-hidden rounded-[1.5rem] bg-[#183927] ring-offset-2 transition hover:ring-2 hover:ring-[#4a8558] ${selectedImage === image ? "ring-2 ring-[#4a8558]" : ""}`}><img src={image} onError={useImageFallback} alt="" className="h-full w-full object-cover" /></button>)}{gallery.length < 2 && <div className="rounded-[1.5rem] bg-[#eaf3e7] p-6"><p className="text-xs font-bold uppercase tracking-[.18em] text-[#4a8558]">VOYARA planner</p><p className="mt-3 text-lg font-black text-[#183927]">Travel, stays, shopping and reviews in one guide.</p></div>}</div>
      </div>
      {destination.photoCredit && <a href={destination.photoCredit.href} target="_blank" rel="noreferrer" className="mt-2 inline-block text-xs text-slate-500 hover:text-[#245239] hover:underline">{destination.photoCredit.label}</a>}
      <nav aria-label="Destination guide sections" className="mt-6 flex gap-2 overflow-x-auto pb-2"><a href="#travel" className="shrink-0 rounded-full bg-white px-4 py-2.5 text-sm font-bold text-[#245239] ring-1 ring-slate-200 hover:bg-[#eef4e9]">Travel</a><a href="#stays" className="shrink-0 rounded-full bg-white px-4 py-2.5 text-sm font-bold text-[#245239] ring-1 ring-slate-200 hover:bg-[#eef4e9]">Stays</a><a href="#shop" className="shrink-0 rounded-full bg-white px-4 py-2.5 text-sm font-bold text-[#245239] ring-1 ring-slate-200 hover:bg-[#eef4e9]">Shop local</a><a href="#reviews" className="shrink-0 rounded-full bg-white px-4 py-2.5 text-sm font-bold text-[#245239] ring-1 ring-slate-200 hover:bg-[#eef4e9]">Reviews</a></nav>

      <div className="mt-9 grid gap-9 lg:grid-cols-[minmax(0,1fr)_330px]">
        <div className="space-y-12">
          <section><div className="flex flex-wrap items-center gap-3"><span className="flex items-center gap-1.5 text-sm font-black"><Star size={17} className="fill-amber-400 text-amber-400" /> {destination.rating}</span><span className="text-sm text-slate-500">{destination.places} places in this guide</span></div><p className="mt-5 max-w-3xl text-lg leading-8 text-slate-600">{destination.overview ?? destination.description}</p></section>
          <section><p className="text-xs font-bold uppercase tracking-[.18em] text-[#4a8558]">See and do</p><h2 className="mt-2 text-3xl font-black tracking-[-.04em]">Highlights in {destination.name}</h2><div className="mt-5 grid gap-4 sm:grid-cols-2">{thingsToDo.map((thing, index) => <div key={thing} className="flex gap-4 rounded-2xl bg-white p-5 shadow-sm ring-1 ring-slate-200"><span className="grid size-9 shrink-0 place-items-center rounded-full bg-[#183927] text-sm font-black text-white">{index + 1}</span><p className="font-bold leading-6">{thing}</p></div>)}</div></section>
          {localPlaces.length > 0 && <section><div className="flex items-end justify-between gap-4"><div><p className="text-xs font-bold uppercase tracking-[.18em] text-[#4a8558]">Local places</p><h2 className="mt-2 text-3xl font-black tracking-[-.04em]">Choose your stops</h2></div><Link to={`/trip-builder?destination=${destination.id}`} className="hidden text-sm font-bold text-[#245239] sm:inline">Add to trip <ArrowRight size={16} className="inline" /></Link></div><div className="mt-5 grid gap-5 sm:grid-cols-2 lg:grid-cols-3">{localPlaces.map((place) => <Link key={place.id} to={`/places/${place.id}`} className="group overflow-hidden rounded-2xl bg-white shadow-sm ring-1 ring-slate-200 transition hover:-translate-y-1 hover:shadow-md"><img src={place.image} onError={useImageFallback} alt={place.name} className="h-40 w-full object-cover" /><div className="p-4"><p className="text-xs font-bold uppercase tracking-wider text-[#4a8558]">{place.type}</p><h3 className="mt-1 text-lg font-black">{place.name}</h3><p className="mt-2 line-clamp-2 text-sm leading-6 text-slate-500">{place.description}</p><span className="mt-3 inline-flex items-center gap-1 text-sm font-bold text-[#245239]">Open guide <ArrowRight size={15} /></span></div></Link>)}</div></section>}
          <section id="travel" className="scroll-mt-7 rounded-[1.8rem] bg-[#183927] p-6 text-white sm:p-8"><p className="text-xs font-bold uppercase tracking-[.18em] text-[#d8fbcc]">Travel smart</p><h2 className="mt-2 text-3xl font-black tracking-[-.04em]">Your {destination.name} travel plan</h2><div className="mt-6 grid gap-4 md:grid-cols-3"><InfoCard icon={<Plane size={19} />} title="Getting there" text={guide.arrivalTip} /><InfoCard icon={<Navigation size={19} />} title="Getting around" text={guide.gettingAround} /><InfoCard icon={<ShieldCheck size={19} />} title="Good to know" text={guide.safetyNote} /></div><div className="mt-7 border-t border-white/15 pt-6"><p className="text-sm font-black text-[#d8fbcc]">A simple, flexible route</p><div className="mt-4 grid gap-3 md:grid-cols-3">{guide.itinerary.map((stop) => <div key={stop.title} className="rounded-2xl bg-white/10 p-4"><p className="text-xs font-bold uppercase tracking-wider text-[#d8fbcc]">{stop.time}</p><h3 className="mt-2 font-black">{stop.title}</h3><p className="mt-2 text-sm leading-6 text-white/75">{stop.description}</p></div>)}</div></div></section>
          <section id="stays" className="scroll-mt-7"><div className="flex flex-wrap items-end justify-between gap-4"><div><p className="text-xs font-bold uppercase tracking-[.18em] text-[#4a8558]">Where to stay</p><h2 className="mt-2 text-3xl font-black tracking-[-.04em]">Stay shortlist & guest feedback</h2></div><Link to="/hotels" className="text-sm font-bold text-[#245239] hover:underline">Compare all stays</Link></div><div className="mt-5 grid gap-5 sm:grid-cols-2">{stayOptions.map((stay) => { const isCatalogStay = stays.some((item) => item.id === stay.id); const card = <article className="overflow-hidden rounded-2xl bg-white shadow-sm ring-1 ring-slate-200"><img src={stay.image} onError={useImageFallback} alt={stay.name} className="h-44 w-full object-cover" /><div className="p-5"><div className="flex items-start justify-between gap-3"><div><p className="text-xs font-bold uppercase tracking-wider text-[#4a8558]">{stay.type}</p><h3 className="mt-1 text-xl font-black">{stay.name}</h3></div><span className="flex shrink-0 items-center gap-1 text-sm font-black text-amber-700"><Star size={14} className="fill-amber-400 text-amber-400" /> {stay.rating}</span></div><p className="mt-2 text-sm text-slate-500">{stay.reviews} traveller reviews</p><div className="mt-4 flex flex-wrap gap-2">{stay.amenities.slice(0, 3).map((amenity) => <span key={amenity} className="rounded-full bg-[#eef4e9] px-2.5 py-1 text-xs font-bold text-[#245239]">{amenity}</span>)}</div><div className="mt-5 flex items-center justify-between border-t border-slate-100 pt-4"><p><b>{formatINR(stay.price)}</b><span className="text-xs text-slate-500"> / night</span></p><span className="text-sm font-bold text-[#245239]">{isCatalogStay ? "View stay" : "Plan stay"} <ArrowRight size={15} className="inline" /></span></div></div></article>; return isCatalogStay ? <Link key={stay.id} to={`/hotels/${stay.id}`} className="block transition hover:-translate-y-1">{card}</Link> : <Link key={stay.id} to={`/trip-builder?destination=${destination.id}`} className="block transition hover:-translate-y-1">{card}</Link>; })}</div></section>
          <section id="shop" className="scroll-mt-7"><div className="flex items-center gap-2"><ShoppingBag size={21} className="text-[#245239]" /><div><p className="text-xs font-bold uppercase tracking-[.18em] text-[#4a8558]">Shop local</p><h2 className="mt-1 text-3xl font-black tracking-[-.04em]">Take a piece of {destination.name} home</h2></div></div><div className="mt-5 grid gap-4 sm:grid-cols-2">{shopping.map((shop) => <article key={shop.id} className="rounded-2xl bg-white p-5 shadow-sm ring-1 ring-slate-200"><p className="text-xs font-bold uppercase tracking-wider text-[#4a8558]">{shop.category}</p><h3 className="mt-2 text-xl font-black">{shop.name}</h3><p className="mt-3 text-sm leading-6 text-slate-500">{shop.description}</p><p className="mt-4 border-t border-slate-100 pt-4 text-sm font-black text-[#245239]">Typical spend: {shop.priceRange}</p></article>)}</div></section>
          <section><div className="flex items-center gap-2"><Utensils size={21} className="text-[#245239]" /><div><p className="text-xs font-bold uppercase tracking-[.18em] text-[#4a8558]">Eat local</p><h2 className="mt-1 text-3xl font-black tracking-[-.04em]">Foods to try</h2></div></div><div className="mt-5 flex flex-wrap gap-2">{foods.map((food) => <span key={food} className="rounded-full bg-[#eaf3e7] px-4 py-2.5 text-sm font-bold text-[#183927]">{food}</span>)}</div>{localRestaurants.length > 0 && <div className="mt-5 grid gap-4 sm:grid-cols-2">{localRestaurants.slice(0, 2).map((restaurant) => <article key={restaurant.id} className="rounded-2xl bg-white p-5 shadow-sm ring-1 ring-slate-200"><div className="flex items-start justify-between gap-4"><div><p className="text-xs font-bold uppercase tracking-wider text-[#4a8558]">{restaurant.cuisine}</p><h3 className="mt-1 text-lg font-black">{restaurant.name}</h3></div><span className="shrink-0 text-sm font-black text-amber-700">★ {restaurant.rating}</span></div><p className="mt-3 text-sm leading-6 text-slate-500">{restaurant.description}</p><p className="mt-4 text-sm font-black">{formatINR(restaurant.priceForTwo)} <span className="font-normal text-slate-500">for two</span></p></article>)}</div>}</section>
          <section id="reviews" className="scroll-mt-7"><div className="flex flex-wrap items-end justify-between gap-4"><div className="flex items-center gap-2"><MessageCircle size={21} className="text-[#245239]" /><div><p className="text-xs font-bold uppercase tracking-[.18em] text-[#4a8558]">Traveller reviews</p><h2 className="mt-1 text-3xl font-black tracking-[-.04em]">What visitors loved</h2></div></div><div className="rounded-2xl bg-[#eef4e9] px-4 py-3 text-right"><p className="flex items-center gap-1 text-lg font-black text-[#183927]"><Star size={16} className="fill-amber-400 text-amber-400" /> {averageReview}</p><p className="text-xs font-semibold text-slate-500">sample guide reviews</p></div></div><div className="mt-5 grid gap-4 sm:grid-cols-2">{reviews.map((review) => <article key={`${review.author}-${review.tripType}`} className="rounded-2xl bg-white p-5 shadow-sm ring-1 ring-slate-200"><div className="flex items-start justify-between gap-3"><div><h3 className="font-black">{review.author}</h3><p className="mt-1 text-xs font-semibold text-slate-500">{review.tripType}</p></div><span className="flex items-center gap-1 text-sm font-black text-amber-700"><Star size={14} className="fill-amber-400 text-amber-400" /> {review.rating}.0</span></div><p className="mt-4 text-sm leading-6 text-slate-600">“{review.comment}”</p></article>)}</div></section>
          <section className="rounded-[1.8rem] bg-[#eaf3e7] p-6 sm:p-8"><p className="text-xs font-bold uppercase tracking-[.18em] text-[#4a8558]">Before you go</p><div className="mt-5 grid gap-4 sm:grid-cols-3">{tips.map((tip) => <p key={tip} className="flex gap-2 text-sm leading-6 text-slate-700"><Check size={17} className="mt-0.5 shrink-0 text-[#387a43]" />{tip}</p>)}</div></section>
        </div>
        <aside className="h-fit lg:sticky lg:top-6"><div className="rounded-[1.8rem] bg-white p-6 shadow-sm ring-1 ring-slate-200"><p className="text-xs font-bold uppercase tracking-[.18em] text-[#4a8558]">Plan your visit</p><p className="mt-4 text-sm text-slate-500">Typical trip budget</p><p className="mt-1 flex items-center gap-2 text-2xl font-black"><Wallet size={21} /> from {formatINR(destination.fromPrice)}</p><div className="my-6 h-px bg-slate-100" /><p className="flex gap-3 text-sm"><CalendarDays size={18} className="shrink-0 text-[#387a43]" /><span><b className="block text-slate-900">Best time</b><span className="mt-1 block text-slate-500">{destination.bestTime}</span></span></p><p className="mt-5 flex gap-3 text-sm"><BedDouble size={18} className="shrink-0 text-[#387a43]" /><span><b className="block text-slate-900">Ideal duration</b><span className="mt-1 block text-slate-500">{guide.idealDuration}</span></span></p><Link to={`/trip-builder?destination=${destination.id}`} className="mt-7 flex w-full items-center justify-center gap-2 rounded-full bg-[#183927] px-5 py-3.5 text-sm font-bold text-white hover:bg-[#245239]">Plan this trip <ArrowRight size={17} /></Link><button type="button" onClick={() => toggleFavorite({ id: destination.id, kind: "destination", title: destination.name, subtitle: `${destination.region}, ${destination.country}`, image: destination.image, href: `/destinations/${destination.id}` })} className="mt-3 flex w-full items-center justify-center gap-2 rounded-full border border-slate-200 px-5 py-3.5 text-sm font-bold hover:bg-slate-50"><Heart size={17} className={saved ? "fill-rose-500 text-rose-500" : ""} /> {saved ? "Saved to favorites" : "Save destination"}</button></div><div className="mt-5 rounded-2xl bg-[#eaf3e7] p-5"><p className="text-sm font-black text-[#183927]">Everything for the day in one place</p><p className="mt-2 text-sm leading-6 text-slate-600">Compare stay feedback, build a route, find local food and save shopping ideas as you plan.</p></div></aside>
      </div>
    </section>
  </main>;
}

function InfoCard({ icon, title, text }: { icon: ReactNode; title: string; text: string }) {
  return <div className="rounded-2xl bg-white/10 p-4"><span className="grid size-9 place-items-center rounded-xl bg-[#d8fbcc] text-[#183927]">{icon}</span><h3 className="mt-4 font-black">{title}</h3><p className="mt-2 text-sm leading-6 text-white/75">{text}</p></div>;
}
