import { ArrowRight, Heart, MapPin, Search, Star } from "lucide-react";
import { useMemo, useState } from "react";
import { Link } from "react-router-dom";
import { categories, destinations, formatINR } from "../data/catalog";
import { useVoyara } from "../context/VoyaraContext";

export default function Destinations() {
  const [query, setQuery] = useState("");
  const [category, setCategory] = useState("All");
  const { favorites, toggleFavorite } = useVoyara();
  const visible = useMemo(() => {
    const search = query.trim().toLowerCase();
    return destinations.filter((destination) => (category === "All" || destination.category === category) && (!search || [destination.name, destination.region, destination.category, destination.description].join(" ").toLowerCase().includes(search)));
  }, [category, query]);

  return <main className="min-h-screen bg-[#fbfaf7] pb-16">
    <section className="bg-[#183927] px-5 py-16 text-white sm:px-8 sm:py-20 lg:px-10"><div className="mx-auto max-w-7xl"><p className="text-xs font-bold uppercase tracking-[.22em] text-[#d8fbcc]">India travel catalogue</p><h1 className="mt-4 max-w-3xl text-4xl font-black tracking-[-.055em] sm:text-6xl">Find a place that feels like a story.</h1><p className="mt-5 max-w-2xl text-base leading-7 text-white/75">Explore destination guides with attractions, local dishes, sample stays and practical trip information. Start with Odisha's Puri–Konark–Bhubaneswar circuit or search across India.</p><label className="mt-8 flex max-w-2xl items-center gap-3 rounded-2xl bg-white px-4 py-3 text-slate-900 shadow-xl"><Search size={20} className="text-slate-400" /><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Search Puri, temples, beaches, food…" className="min-w-0 flex-1 bg-transparent text-sm font-semibold outline-none placeholder:font-normal placeholder:text-slate-400" /></label></div></section>
    <section className="mx-auto max-w-7xl px-5 py-10 sm:px-8 lg:px-10"><div className="flex gap-2 overflow-x-auto pb-2">{["All", ...categories].map((item) => <button key={item} type="button" onClick={() => setCategory(item)} className={"shrink-0 rounded-full px-4 py-2.5 text-sm font-bold transition " + (category === item ? "bg-[#183927] text-white" : "bg-white text-slate-600 ring-1 ring-slate-200 hover:bg-slate-50")}>{item}</button>)}</div><div className="mt-10 flex items-end justify-between gap-5"><div><p className="text-xs font-bold uppercase tracking-[.18em] text-[#4a8558]">Curated destination guides</p><h2 className="mt-2 text-3xl font-black tracking-[-.04em]">{visible.length} places to explore</h2></div></div>
      {visible.length === 0 ? <div className="mt-8 rounded-3xl bg-white px-6 py-16 text-center ring-1 ring-slate-200"><Search size={28} className="mx-auto text-slate-400" /><h3 className="mt-4 text-xl font-black">No destination matches that search.</h3><button type="button" onClick={() => { setQuery(""); setCategory("All"); }} className="mt-5 rounded-full bg-[#183927] px-5 py-3 text-sm font-bold text-white">Clear filters</button></div> : <div className="mt-8 grid gap-6 sm:grid-cols-2 lg:grid-cols-3">{visible.map((destination) => { const saved = favorites.some((item) => item.kind === "destination" && item.id === destination.id); return <article key={destination.id} className="group overflow-hidden rounded-[1.6rem] bg-white shadow-sm ring-1 ring-slate-200 transition hover:-translate-y-1 hover:shadow-xl"><div className="relative h-60 overflow-hidden"><img src={destination.image} alt={destination.name} className="h-full w-full object-cover transition duration-500 group-hover:scale-105" /><div className="absolute inset-0 bg-gradient-to-t from-black/55 to-transparent" /><span className="absolute left-4 top-4 rounded-full bg-white/90 px-3 py-1.5 text-xs font-bold text-slate-900">{destination.category}</span><button type="button" onClick={() => toggleFavorite({ id: destination.id, kind: "destination", title: destination.name, subtitle: destination.region + ", " + destination.country, image: destination.image, href: "/destinations/" + destination.id })} aria-label={(saved ? "Remove " : "Save ") + destination.name} className="absolute right-4 top-4 grid size-10 place-items-center rounded-full bg-white/90 text-slate-800"><Heart size={18} className={saved ? "fill-rose-500 text-rose-500" : ""} /></button><p className="absolute bottom-4 left-4 flex items-center gap-1.5 text-sm font-bold text-white"><MapPin size={15} /> {destination.region}</p></div><div className="p-5"><div className="flex items-start justify-between gap-4"><h3 className="text-2xl font-black tracking-[-.03em]">{destination.name}</h3><span className="flex items-center gap-1 text-sm font-bold text-amber-700"><Star size={15} className="fill-amber-400 text-amber-400" />{destination.rating}</span></div><p className="mt-3 min-h-12 text-sm leading-6 text-slate-500">{destination.description}</p><div className="mt-5 flex items-center justify-between border-t border-slate-100 pt-4"><span className="text-sm font-bold">from {formatINR(destination.fromPrice)}</span><Link to={"/destinations/" + destination.id} className="inline-flex items-center gap-1.5 text-sm font-bold text-[#245239]">View guide <ArrowRight size={16} /></Link></div></div></article>; })}</div>}
    </section>
  </main>;
}
