import { Heart, MapPin, Search, Trash2 } from "lucide-react";
import { useMemo, useState } from "react";
import { Link } from "react-router-dom";
import { useVoyara } from "../context/VoyaraContext";
import type { FavoriteKind } from "../types/domain";

const tabs: { label: string; kind: FavoriteKind | "all" }[] = [{ label: "All saved", kind: "all" }, { label: "Destinations", kind: "destination" }, { label: "Stays", kind: "stay" }, { label: "Places", kind: "place" }, { label: "Trips", kind: "trip" }];

export default function FavoritesPage() {
  const { favorites, toggleFavorite } = useVoyara();
  const [active, setActive] = useState<FavoriteKind | "all">("all");
  const displayed = useMemo(() => active === "all" ? favorites : favorites.filter((item) => item.kind === active), [active, favorites]);
  return <main className="min-h-[70vh] bg-[#fbfaf7] px-5 py-12 sm:px-8 lg:px-10"><div className="mx-auto max-w-6xl"><p className="text-xs font-bold uppercase tracking-[.18em] text-[#4a8558]">Your collection</p><h1 className="mt-3 text-4xl font-black tracking-[-.045em] sm:text-5xl">Saved for later.</h1><p className="mt-3 max-w-xl leading-7 text-slate-500">Keep a shortlist of places worth daydreaming about. Your saved ideas are stored in this browser during the demo.</p><div className="mt-8 flex gap-2 overflow-x-auto pb-2">{tabs.map((tab) => <button key={tab.kind} type="button" onClick={() => setActive(tab.kind)} className={`shrink-0 rounded-full px-4 py-2.5 text-sm font-bold transition ${active === tab.kind ? "bg-[#183927] text-white" : "bg-white text-slate-600 ring-1 ring-slate-200 hover:bg-slate-100"}`}>{tab.label}{tab.kind === "all" && favorites.length > 0 ? ` (${favorites.length})` : ""}</button>)}</div>{displayed.length === 0 ? <div className="mt-8 rounded-[1.8rem] border border-dashed border-slate-300 bg-white px-6 py-20 text-center"><span className="mx-auto grid size-14 place-items-center rounded-2xl bg-rose-50 text-rose-500"><Heart size={25} /></span><h2 className="mt-5 text-2xl font-black">Nothing saved here yet.</h2><p className="mx-auto mt-2 max-w-sm text-slate-500">Tap the heart on a destination or stay to build a collection for your next trip.</p><Link to="/explore" className="mt-6 inline-flex items-center gap-2 rounded-full bg-[#183927] px-5 py-3 text-sm font-bold text-white"><Search size={16} /> Explore destinations</Link></div> : <div className="mt-8 grid gap-5 sm:grid-cols-2 lg:grid-cols-3">{displayed.map((favorite) => <article key={`${favorite.kind}-${favorite.id}`} className="overflow-hidden rounded-[1.5rem] bg-white shadow-sm ring-1 ring-slate-200"><img src={favorite.image} alt="" className="h-48 w-full object-cover" /><div className="p-5"><div className="flex items-start justify-between gap-4"><div><p className="text-xs font-bold uppercase tracking-wider text-[#4a8558]">{favorite.kind}</p><h2 className="mt-1 text-xl font-black">{favorite.title}</h2><p className="mt-2 flex items-center gap-1.5 text-sm text-slate-500"><MapPin size={15} /> {favorite.subtitle}</p></div><button type="button" onClick={() => toggleFavorite(favorite)} aria-label={`Remove ${favorite.title}`} className="grid size-9 place-items-center rounded-full bg-rose-50 text-rose-500 hover:bg-rose-100"><Trash2 size={16} /></button></div><Link to={favorite.href} className="mt-5 inline-block text-sm font-bold text-[#245239] hover:underline">View details</Link></div></article>)}</div>}</div></main>;
}
