import { ArrowRight, Bot, CalendarDays, Heart, MapPin, Search, ShieldCheck, Sparkles, Star } from "lucide-react";
import { useState, type FormEvent } from "react";
import { Link, useNavigate } from "react-router-dom";
import Navbar from "../components/Navbar";
import { useVoyara } from "../context/VoyaraContext";
import { categories, destinations, formatINR, stays } from "../data/catalog";

const testimonials = [
  ["“The itinerary felt surprisingly personal. We found quiet spots in Manali we would have missed.”", "Rhea M.", "Bengaluru"],
  ["“One place for saving ideas, finding stays and making the actual plan. That is rare.”", "Aman K.", "New Delhi"],
];

export default function Home() {
  const navigate = useNavigate();
  const { favorites, toggleFavorite } = useVoyara();
  const [query, setQuery] = useState("");
  const isSaved = (id: string) => favorites.some((item) => item.id === id && item.kind === "destination");
  const submitSearch = (event: FormEvent<HTMLFormElement>) => {
    event.preventDefault();
    navigate(`/search${query.trim() ? `?q=${encodeURIComponent(query.trim())}` : ""}`);
  };

  return (
    <main className="overflow-hidden bg-[#fbfaf7] text-slate-950">
      <section className="relative isolate min-h-[740px] overflow-hidden bg-slate-950">
        <img src="https://images.unsplash.com/photo-1469474968028-56623f02e42e?auto=format&fit=crop&w=2400&q=90" alt="Mountain valley at sunrise" className="absolute inset-0 -z-20 h-full w-full object-cover" />
        <div className="absolute inset-0 -z-10 bg-[linear-gradient(90deg,rgba(8,15,28,.86),rgba(8,15,28,.38),rgba(8,15,28,.2))]" />
        <Navbar />
        <div className="mx-auto flex min-h-[740px] max-w-7xl items-center px-5 pb-16 pt-28 sm:px-8 lg:px-10">
          <div className="max-w-3xl">
            <p className="inline-flex items-center gap-2 rounded-full border border-white/20 bg-white/10 px-4 py-2 text-sm font-semibold text-white/90 backdrop-blur"><Sparkles size={16} className="text-amber-300" /> Thoughtfully planned. Wonderfully yours.</p>
            <h1 className="mt-7 text-5xl font-black leading-[.98] tracking-[-.055em] text-white sm:text-6xl lg:text-8xl">Where will you<br /><span className="text-[#d8fbcc]">go next?</span></h1>
            <p className="mt-6 max-w-xl text-base leading-7 text-white/75 sm:text-lg">Discover places that stay with you. VOYARA brings destinations, exceptional stays and intelligent trip planning into one calm journey.</p>
            <form onSubmit={submitSearch} className="mt-9 max-w-3xl rounded-[1.35rem] bg-white p-2.5 shadow-2xl shadow-black/25 sm:flex sm:items-center">
              <div className="flex flex-1 items-center gap-3 px-3 py-2.5"><span className="grid size-11 shrink-0 place-items-center rounded-xl bg-[#eef8ea] text-[#387a43]"><MapPin size={20} /></span><label className="min-w-0 flex-1"><span className="block text-[11px] font-bold uppercase tracking-[.15em] text-slate-400">Explore anywhere</span><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Search cities, destinations, stays…" className="mt-0.5 w-full bg-transparent text-sm font-semibold text-slate-900 outline-none placeholder:font-normal placeholder:text-slate-400" /></label></div>
              <button type="submit" className="mt-1 flex w-full items-center justify-center gap-2 rounded-xl bg-[#183927] px-6 py-3.5 text-sm font-bold text-white transition hover:bg-[#245239] sm:mt-0 sm:w-auto"><Search size={18} /> Search</button>
            </form>
            <div className="mt-5 flex flex-wrap items-center gap-2 text-sm text-white/65"><span>Popular:</span>{["Manali", "Bali", "Jaipur", "Kyoto"].map((term) => <button key={term} type="button" onClick={() => navigate(`/search?q=${term}`)} className="rounded-full border border-white/15 bg-white/10 px-3 py-1.5 text-white/90 transition hover:bg-white/20">{term}</button>)}</div>
          </div>
        </div>
        <div className="absolute bottom-6 left-1/2 hidden w-full max-w-7xl -translate-x-1/2 px-10 lg:flex"><div className="flex items-center gap-7 text-sm text-white/75"><span className="flex items-center gap-2"><ShieldCheck size={17} className="text-[#d8fbcc]" /> Curated stays</span><span className="flex items-center gap-2"><Star size={17} className="fill-amber-300 text-amber-300" /> Rated by real travellers</span></div></div>
      </section>

      <section className="mx-auto max-w-7xl px-5 py-20 sm:px-8 lg:px-10 lg:py-28">
        <div className="flex flex-col justify-between gap-5 sm:flex-row sm:items-end"><div><p className="text-xs font-bold uppercase tracking-[.18em] text-[#4a8558]">Start somewhere beautiful</p><h2 className="mt-3 text-4xl font-black tracking-[-.045em] sm:text-5xl">Places people are<br className="hidden sm:block" /> talking about.</h2></div><Link to="/destinations" className="inline-flex items-center gap-2 font-bold text-[#245239] hover:text-[#183927]">Explore all destinations <ArrowRight size={18} /></Link></div>
        <div className="mt-11 grid gap-5 sm:grid-cols-2 lg:grid-cols-4">
          {destinations.map((destination) => {
            const saved = isSaved(destination.id);
            return <article key={destination.id} className="group overflow-hidden rounded-[1.6rem] bg-white shadow-sm ring-1 ring-slate-200/80 transition duration-300 hover:-translate-y-1.5 hover:shadow-xl"><div className="relative h-72 overflow-hidden"><img src={destination.image} alt={destination.name} loading="lazy" className="h-full w-full object-cover transition duration-700 group-hover:scale-110" /><div className="absolute inset-0 bg-gradient-to-t from-black/55 via-transparent to-transparent" /><button type="button" aria-label={`Save ${destination.name}`} onClick={() => toggleFavorite({ id: destination.id, kind: "destination", title: destination.name, subtitle: `${destination.region}, ${destination.country}`, image: destination.image, href: `/destinations/${destination.id}` })} className="absolute right-4 top-4 grid size-10 place-items-center rounded-full bg-white/90 text-slate-800 backdrop-blur hover:bg-white"><Heart size={18} className={saved ? "fill-rose-500 text-rose-500" : ""} /></button><div className="absolute bottom-4 left-4 text-white"><p className="text-xs font-bold uppercase tracking-wider text-white/75">{destination.category}</p><h3 className="mt-0.5 text-2xl font-black">{destination.name}</h3></div></div><div className="p-4"><div className="flex items-center justify-between text-sm"><span className="flex items-center gap-1.5 text-slate-500"><Star size={15} className="fill-amber-400 text-amber-400" /> <b className="text-slate-800">{destination.rating}</b> · {destination.places} places</span><span className="font-bold text-slate-900">from {formatINR(destination.fromPrice)}</span></div><Link to={`/destinations/${destination.id}`} className="mt-4 flex items-center justify-between border-t border-slate-100 pt-3 text-sm font-bold text-[#245239]">Discover this place <ArrowRight size={16} /></Link></div></article>;
          })}
        </div>
      </section>

      <section className="border-y border-[#e8ece3] bg-[#f1f6ed]"><div className="mx-auto max-w-7xl px-5 py-16 sm:px-8 lg:px-10"><div className="flex flex-wrap gap-2.5">{categories.map((category) => <Link key={category} to={`/explore?category=${encodeURIComponent(category)}`} className="rounded-full border border-[#cadac8] bg-white px-4 py-2.5 text-sm font-bold text-slate-700 transition hover:border-[#4a8558] hover:bg-[#e4f2df]">{category}</Link>)}</div><div className="mt-10 grid gap-8 lg:grid-cols-[1fr_1.1fr]"><div><p className="text-xs font-bold uppercase tracking-[.18em] text-[#4a8558]">One question, a whole journey</p><h2 className="mt-3 max-w-lg text-4xl font-black tracking-[-.045em] sm:text-5xl">Meet the travel assistant that actually listens.</h2><p className="mt-5 max-w-lg leading-7 text-slate-600">Tell it your days, budget and the kind of memories you want to make. It turns your ideas into a grounded, editable trip plan.</p><Link to="/ai-assistant" className="mt-7 inline-flex items-center gap-2 rounded-full bg-[#183927] px-5 py-3 font-bold text-white transition hover:bg-[#245239]"><Bot size={18} /> Plan with VOYARA AI <ArrowRight size={17} /></Link></div><div className="rounded-[1.8rem] bg-[#183927] p-6 text-white shadow-xl sm:p-8"><div className="flex items-center gap-3"><span className="grid size-10 place-items-center rounded-2xl bg-[#d8fbcc] text-[#183927]"><Sparkles size={19} /></span><div><p className="font-bold">VOYARA Assistant</p><p className="text-sm text-white/55">Travel planner · Online</p></div></div><div className="mt-8 ml-auto max-w-sm rounded-2xl rounded-tr-sm bg-white/10 p-4 text-sm leading-6 text-white/90">I have 5 days, a ₹30,000 budget, and I want mountains and peaceful places.</div><div className="mt-3 max-w-sm rounded-2xl rounded-tl-sm bg-[#d8fbcc] p-4 text-sm leading-6 text-[#183927]">Manali would be a lovely fit. I can build a 5-day plan with stays, Solang Valley and Old Manali—shall we start?</div><div className="mt-7 flex items-center gap-2 rounded-xl border border-white/15 bg-white/5 px-4 py-3 text-sm text-white/45">Ask about your next trip <ArrowRight size={16} className="ml-auto" /></div></div></div></div></section>

      <section className="mx-auto max-w-7xl px-5 py-20 sm:px-8 lg:px-10 lg:py-28"><div className="flex items-end justify-between gap-5"><div><p className="text-xs font-bold uppercase tracking-[.18em] text-[#4a8558]">Stay well</p><h2 className="mt-3 text-4xl font-black tracking-[-.045em] sm:text-5xl">A better kind of stay.</h2></div><Link to="/hotels" className="hidden items-center gap-2 font-bold text-[#245239] sm:inline-flex">See all stays <ArrowRight size={18} /></Link></div><div className="mt-11 grid gap-6 md:grid-cols-3">{stays.map((stay) => <article key={stay.id} className="group overflow-hidden rounded-[1.6rem] bg-white shadow-sm ring-1 ring-slate-200/80"><img src={stay.image} alt={stay.name} loading="lazy" className="h-60 w-full object-cover transition duration-500 group-hover:scale-105" /><div className="p-5"><div className="flex items-start justify-between gap-4"><div><p className="text-xs font-bold uppercase tracking-wider text-[#4a8558]">{stay.type}</p><h3 className="mt-1 text-xl font-black">{stay.name}</h3><p className="mt-1 text-sm text-slate-500">{stay.destination}</p></div><span className="flex items-center gap-1 rounded-full bg-amber-50 px-2.5 py-1 text-sm font-bold text-amber-800"><Star size={14} className="fill-amber-400 text-amber-400" /> {stay.rating}</span></div><div className="mt-5 flex items-end justify-between border-t border-slate-100 pt-4"><p><span className="text-lg font-black">{formatINR(stay.price)}</span><span className="text-xs text-slate-500"> / night</span></p><Link to={`/booking/${stay.id}`} className="text-sm font-bold text-[#245239]">View stay</Link></div></div></article>)}</div></section>

      <section className="bg-[#183927] px-5 py-20 text-white sm:px-8 lg:px-10"><div className="mx-auto grid max-w-7xl gap-10 lg:grid-cols-[1fr_1.2fr]"><div><p className="text-xs font-bold uppercase tracking-[.18em] text-[#d8fbcc]">Travelled, then told</p><h2 className="mt-4 text-4xl font-black tracking-[-.045em] sm:text-5xl">Real stories from people who went.</h2><div className="mt-8 flex items-center gap-1 text-amber-300">{Array.from({ length: 5 }, (_, index) => <Star key={index} size={19} fill="currentColor" />)} <span className="ml-2 text-sm font-semibold text-white/70">Loved by early VOYARA travellers</span></div></div><div className="grid gap-4 sm:grid-cols-2">{testimonials.map(([quote, name, city]) => <figure key={name} className="flex flex-col justify-between rounded-[1.5rem] bg-white/10 p-6"><blockquote className="text-lg leading-7 text-white/90">{quote}</blockquote><figcaption className="mt-8 text-sm"><b className="block">{name}</b><span className="text-white/50">{city}</span></figcaption></figure>)}</div></div></section>

      <section className="px-5 py-16 sm:px-8"><div className="mx-auto flex max-w-7xl flex-col justify-between gap-6 rounded-[1.8rem] bg-[#eef4e9] px-6 py-8 sm:px-9 lg:flex-row lg:items-center"><div><p className="flex items-center gap-2 text-sm font-bold text-[#4a8558]"><CalendarDays size={17} /> Travel notes, without the noise</p><h2 className="mt-2 text-2xl font-black tracking-tight">Get one beautiful idea for your next trip.</h2></div><form onSubmit={(event) => event.preventDefault()} className="flex w-full max-w-md gap-2"><input type="email" required placeholder="Your email address" className="min-w-0 flex-1 rounded-xl border border-[#cbd9c8] bg-white px-4 py-3 text-sm outline-none ring-[#4a8558] focus:ring-2" /><button className="rounded-xl bg-[#183927] px-5 py-3 text-sm font-bold text-white">Subscribe</button></form></div></section>
      <footer className="border-t border-slate-200 px-5 py-10 sm:px-8"><div className="mx-auto flex max-w-7xl flex-col justify-between gap-5 text-sm text-slate-500 sm:flex-row"><p className="font-black tracking-[.14em] text-slate-900">VOYARA</p><div className="flex flex-wrap gap-5"><Link to="/explore" className="hover:text-slate-950">Explore</Link><Link to="/ai-assistant" className="hover:text-slate-950">AI assistant</Link><Link to="/settings" className="hover:text-slate-950">Settings</Link></div><p>© {new Date().getFullYear()} VOYARA</p></div></footer>
    </main>
  );
}
