import { AlertTriangle, ArrowLeft, Check, Heart, Hotel, Minus, Plus, Star, Users, Wifi } from "lucide-react";
import { useState } from "react";
import { Link, useParams } from "react-router-dom";
import { useVoyara } from "../context/VoyaraContext";
import { formatINR, stays } from "../data/catalog";
import { getOccupancy } from "../lib/roomOccupancy";

function Counter({ label, note, value, min, onChange }: { label: string; note: string; value: number; min: number; onChange: (value: number) => void }) {
  return <div className="flex items-center justify-between gap-3 rounded-2xl bg-slate-50 p-3.5"><div><p className="font-bold">{label}</p><p className="mt-0.5 text-xs text-slate-500">{note}</p></div><div className="flex items-center gap-2"><button type="button" aria-label={"Decrease " + label} onClick={() => onChange(Math.max(min, value - 1))} className="grid size-8 place-items-center rounded-full bg-white text-slate-700 shadow-sm"><Minus size={15} /></button><span className="w-5 text-center text-sm font-black">{value}</span><button type="button" aria-label={"Increase " + label} onClick={() => onChange(value + 1)} className="grid size-8 place-items-center rounded-full bg-[#183927] text-white"><Plus size={15} /></button></div></div>;
}

export default function HotelDetailsPage() {
  const { id } = useParams();
  const stay = stays.find((item) => item.id === id);
  const { favorites, toggleFavorite } = useVoyara();
  const [rooms, setRooms] = useState(1);
  const [adults, setAdults] = useState(2);
  const [children, setChildren] = useState(0);
  if (!stay) return <main className="grid min-h-[65vh] place-items-center bg-[#fbfaf7] px-5 text-center"><div><h1 className="text-3xl font-black">Stay not found</h1><p className="mt-2 text-slate-500">It may no longer be included in this catalogue.</p><Link to="/hotels" className="mt-6 inline-flex rounded-full bg-[#183927] px-5 py-3 text-sm font-bold text-white">Browse stays</Link></div></main>;

  const saved = favorites.some((item) => item.id === stay.id && item.kind === "stay");
  const occupancy = getOccupancy(adults, children, rooms, stay.childExtraBedFee);
  const estimatedCost = stay.price * rooms + occupancy.childAccommodationCost;

  return <main className="bg-[#fbfaf7] px-5 py-7 sm:px-8 lg:px-10"><div className="mx-auto max-w-6xl"><Link to="/hotels" className="inline-flex items-center gap-2 text-sm font-bold text-slate-600 hover:text-slate-950"><ArrowLeft size={17} /> All stays</Link><section className="mt-6 overflow-hidden rounded-[2rem] bg-white shadow-sm ring-1 ring-slate-200"><div className="grid lg:grid-cols-[1.1fr_.9fr]"><img src={stay.image} alt={stay.name} className="h-[320px] w-full object-cover lg:h-full" /><div className="p-7 sm:p-9"><div className="flex items-start justify-between gap-5"><div><p className="text-xs font-bold uppercase tracking-[.17em] text-[#4a8558]">{stay.type}</p><h1 className="mt-2 text-4xl font-black tracking-[-.05em]">{stay.name}</h1><p className="mt-3 text-slate-500">{stay.destination}, {stay.state}</p></div><button type="button" aria-label={"Save " + stay.name} onClick={() => toggleFavorite({ id: stay.id, kind: "stay", title: stay.name, subtitle: stay.destination, image: stay.image, href: "/hotels/" + stay.id })} className="grid size-11 place-items-center rounded-full bg-rose-50 text-rose-500 hover:bg-rose-100"><Heart size={19} className={saved ? "fill-current" : ""} /></button></div><div className="mt-7 flex items-center gap-3 border-y border-slate-100 py-5"><span className="flex items-center gap-1.5 text-lg font-black"><Star size={18} className="fill-amber-400 text-amber-400" /> {stay.rating}</span><span className="text-sm text-slate-500">Excellent · {stay.reviews} traveller reviews</span></div><p className="mt-6 leading-7 text-slate-600">Thoughtful spaces, a welcoming team and practical details designed to make the end of a full travel day feel easy.</p><div className="mt-6 grid grid-cols-2 gap-3">{stay.amenities.map((amenity) => <p key={amenity} className="flex items-center gap-2 text-sm font-semibold"><span className="grid size-6 place-items-center rounded-full bg-[#eef4e9] text-[#387a43]"><Check size={14} /></span>{amenity}</p>)}<p className="flex items-center gap-2 text-sm font-semibold"><span className="grid size-6 place-items-center rounded-full bg-[#eef4e9] text-[#387a43]"><Wifi size={14} /></span>Wi-Fi included</p></div></div></div>
        <div className="border-t border-slate-200 p-6 sm:px-9"><div className="flex flex-wrap items-end justify-between gap-3"><p><span className="text-2xl font-black">{formatINR(stay.price)}</span><span className="ml-1 text-sm text-slate-500">per room / night</span></p><p className="text-sm text-slate-500">Child extra bed: {formatINR(occupancy.childExtraBedFee)} / night</p></div><div className="mt-5 grid gap-3 md:grid-cols-3"><Counter label="Rooms" note="Up to 4 guests each" value={rooms} min={1} onChange={setRooms} /><Counter label="Adults" note="Age 13+" value={adults} min={1} onChange={setAdults} /><Counter label="Children" note="Age 2–12" value={children} min={0} onChange={setChildren} /></div><div className={"mt-4 rounded-2xl border p-4 " + (occupancy.isValid ? "border-emerald-200 bg-emerald-50" : "border-amber-200 bg-amber-50")}><div className="flex gap-3"><span className="mt-0.5">{occupancy.isValid ? <Check size={18} /> : <AlertTriangle size={18} />}</span><div><p className="text-sm font-bold">{occupancy.message}</p>{!occupancy.isValid && <button type="button" onClick={() => setRooms(occupancy.requiredRooms)} className="mt-3 rounded-full bg-amber-900 px-4 py-2 text-xs font-bold text-white">Use {occupancy.requiredRooms} rooms</button>}</div></div></div><div className="mt-5 flex flex-col justify-between gap-3 rounded-2xl bg-slate-50 p-4 sm:flex-row sm:items-center"><p className="text-sm text-slate-600"><Hotel size={16} className="mr-1 inline" /> {rooms} room{rooms === 1 ? "" : "s"} · <Users size={16} className="mr-1 inline" /> {occupancy.totalGuests} guests</p><p className="text-lg font-black">Estimated: {formatINR(estimatedCost)} <span className="text-xs font-normal text-slate-500">for 1 night</span></p></div><Link to={"/booking/" + stay.id} state={{ stay: stay.name, destination: stay.destination, rooms, adults, children, estimatedCost, childExtraBedFee: occupancy.childExtraBedFee }} aria-disabled={!occupancy.isValid} onClick={(event) => { if (!occupancy.isValid) event.preventDefault(); }} className={"mt-5 flex items-center justify-center rounded-full px-6 py-3.5 text-sm font-bold text-white " + (occupancy.isValid ? "bg-[#183927] hover:bg-[#245239]" : "cursor-not-allowed bg-slate-300")}>{occupancy.isValid ? "Continue to booking" : "Add required rooms to continue"}</Link></div>
      </section></div></main>;
}
