// ===== SIGNATURE EXPERIENCES =====
const signatureData = [
  {
    icon: "fa-utensils",
    title: "Signature Dining",
    desc: "An immersive fine-dining experience with a curated multi-course menu.",
  },
  {
    icon: "fa-kitchen-set",
    title: "Chef's Tasting Menu",
    desc: "An exclusive 12-course journey through Chef Arjun's culinary vision.",
  },
  {
    icon: "fa-champagne-glasses",
    title: "Private Dining",
    desc: "Intimate spaces for romantic dinners, family gatherings, and celebrations.",
  },
  {
    icon: "fa-cake-candles",
    title: "Curated Celebrations",
    desc: "Customized menus and setups for weddings, anniversaries, and milestones.",
  },
];

// ===== DISHES (full menu) =====
const allMenuItems = [
  {
    id: 1,
    name: "Truffle Mushroom Risotto",
    desc: "Creamy Arborio rice with wild mushrooms, truffle oil, and Parmesan.",
    price: 895,
    category: "Continental",
    veg: true,
    vegan: false,
    spicy: false,
    calories: "420 kcal",
  },
  {
    id: 2,
    name: "Saffron Butter Paneer",
    desc: "House-made paneer in a rich saffron-infused tomato butter gravy.",
    price: 745,
    category: "Indian",
    veg: true,
    vegan: false,
    spicy: true,
    calories: "560 kcal",
  },
  {
    id: 3,
    name: "Charcoal Tandoori Salmon",
    desc: "Scottish salmon marinated in charcoal spices, grilled to perfection.",
    price: 1295,
    category: "Indian",
    veg: false,
    vegan: false,
    spicy: true,
    calories: "480 kcal",
  },
  {
    id: 4,
    name: "Royal Awadhi Biryani",
    desc: "Fragrant basmati layered with slow-cooked meat, saffron, and spices.",
    price: 995,
    category: "Indian",
    veg: false,
    vegan: false,
    spicy: true,
    calories: "720 kcal",
  },
  {
    id: 5,
    name: "AURA Chocolate Sphere",
    desc: "Decadent dark chocolate dome with molten hazelnut center.",
    price: 695,
    category: "Desserts",
    veg: true,
    vegan: false,
    spicy: false,
    calories: "380 kcal",
  },
  {
    id: 6,
    name: "Mango & Cardamom Panna Cotta",
    desc: "Silky panna cotta infused with cardamom, topped with mango coulis.",
    price: 595,
    category: "Desserts",
    veg: true,
    vegan: false,
    spicy: false,
    calories: "290 kcal",
  },
  {
    id: 7,
    name: "Crispy Calamari",
    desc: "Lightly fried calamari with a hint of chili and lime.",
    price: 695,
    category: "Starters",
    veg: false,
    vegan: false,
    spicy: false,
    calories: "310 kcal",
  },
  {
    id: 8,
    name: "Grilled Asparagus Salad",
    desc: "Fresh asparagus, cherry tomatoes, and feta with lemon vinaigrette.",
    price: 545,
    category: "Soups & Salads",
    veg: true,
    vegan: false,
    spicy: false,
    calories: "220 kcal",
  },
  {
    id: 9,
    name: "Thai Green Curry",
    desc: "Coconut-based curry with vegetables and aromatic Thai herbs.",
    price: 845,
    category: "Asian",
    veg: true,
    vegan: true,
    spicy: true,
    calories: "490 kcal",
  },
  {
    id: 10,
    name: "Butter Chicken",
    desc: "Classic North Indian chicken in a rich tomato and butter gravy.",
    price: 995,
    category: "Indian",
    veg: false,
    vegan: false,
    spicy: true,
    calories: "680 kcal",
  },
  {
    id: 11,
    name: "Mango Lassi",
    desc: "Sweetened yogurt drink with fresh mango pulp.",
    price: 295,
    category: "Beverages",
    veg: true,
    vegan: false,
    spicy: false,
    calories: "180 kcal",
  },
  {
    id: 12,
    name: "Virgin Mojito",
    desc: "Fresh mint, lime, and soda — a refreshing mocktail.",
    price: 345,
    category: "Mocktails",
    veg: true,
    vegan: true,
    spicy: false,
    calories: "120 kcal",
  },
  {
    id: 13,
    name: "Kids Cheese Pizza",
    desc: "Mini pizza with tomato sauce and mozzarella.",
    price: 395,
    category: "Kids Menu",
    veg: true,
    vegan: false,
    spicy: false,
    calories: "340 kcal",
  },
  {
    id: 14,
    name: "Masala Chai",
    desc: "Traditional Indian spiced tea with milk and ginger.",
    price: 195,
    category: "Beverages",
    veg: true,
    vegan: false,
    spicy: false,
    calories: "90 kcal",
  },
  {
    id: 15,
    name: "Lobster Thermidor",
    desc: "Fresh lobster baked in a creamy mustard and cheese sauce.",
    price: 1595,
    category: "Seafood",
    veg: false,
    vegan: false,
    spicy: false,
    calories: "650 kcal",
  },
  {
    id: 16,
    name: "Margherita Pizza",
    desc: "Wood-fired pizza with fresh mozzarella, basil, and tomato sauce.",
    price: 695,
    category: "Italian",
    veg: true,
    vegan: false,
    spicy: false,
    calories: "540 kcal",
  },
  {
    id: 17,
    name: "Chicken Caesar Salad",
    desc: "Grilled chicken, romaine lettuce, parmesan, and Caesar dressing.",
    price: 645,
    category: "Salads",
    veg: false,
    vegan: false,
    spicy: false,
    calories: "380 kcal",
  },
  {
    id: 18,
    name: "Paneer Tikka Platter",
    desc: "Chargrilled paneer cubes served with mint chutney.",
    price: 295,
    category: "Starters",
    veg: true,
    vegan: false,
    spicy: true,
    calories: "410 kcal",
  },
  {
    id: 19,
    name: "Mutton Rogan Josh",
    desc: "Slow-cooked Kashmiri lamb curry with aromatic spices.",
    price: 500,
    category: "Indian",
    veg: false,
    vegan: false,
    spicy: true,
    calories: "720 kcal",
  },
  {
    id: 20,
    name: "Veg Hakka Noodles",
    desc: "Wok-tossed noodles with vegetables and Asian sauces.",
    price: 145,
    category: "Asian",
    veg: true,
    vegan: true,
    spicy: true,
    calories: "450 kcal",
  },
  {
    id: 21,
    name: "Blueberry Cheesecake",
    desc: "Creamy cheesecake topped with fresh blueberry compote.",
    price: 495,
    category: "Desserts",
    veg: true,
    vegan: false,
    spicy: false,
    calories: "340 kcal",
  },
  {
    id: 22,
    name: "Hot Chocolate Brownie",
    desc: "Warm chocolate brownie served with vanilla ice cream.",
    price: 445,
    category: "Desserts",
    veg: true,
    vegan: false,
    spicy: false,
    calories: "430 kcal",
  },
  {
    id: 23,
    name: "Fresh Lime Soda",
    desc: "Refreshing lime soda served sweet, salted, or mixed.",
    price: 195,
    category: "Beverages",
    veg: true,
    vegan: true,
    spicy: false,
    calories: "80 kcal",
  },
  {
    id: 24,
    name: "Strawberry Mocktail",
    desc: "Fresh strawberries blended with mint and sparkling water.",
    price: 295,
    category: "Mocktails",
    veg: true,
    vegan: true,
    spicy: false,
    calories: "110 kcal",
  },
  {
    id: 25,
    name: "Chicken Tikka",
    desc: "Juicy chicken pieces marinated with Indian spices.",
    price: 395,
    category: "Starters",
    veg: false,
    vegan: false,
    spicy: true,
    calories: "320 kcal",
    img: "https://images.unsplash.com/photo-1603894584373-5ac82b2ae398?w=800&q=80",
  },

  {
    id: 26,
    name: "Veg Manchurian",
    desc: "Crispy vegetable balls tossed in spicy Indo-Chinese sauce.",
    price: 245,
    category: "Asian",
    veg: true,
    vegan: true,
    spicy: true,
    calories: "280 kcal",
    img: "https://images.unsplash.com/photo-1512058564366-18510be2db19?w=800&q=80",
  },

  {
    id: 27,
    name: "Fish Fry",
    desc: "Golden fried fish fillets served with tartar sauce.",
    price: 495,
    category: "Seafood",
    veg: false,
    vegan: false,
    spicy: false,
    calories: "410 kcal",
    img: "https://images.unsplash.com/photo-1544025162-d76694265947?w=800&q=80",
  },
];

// ===== EVENTS =====
const eventsData = [
  {
    id: 1,
    title: "Live Music Evening",
    date: "Dec 15, 2026",
    time: "7:00 PM – 10:00 PM",
    desc: "An evening of soulful jazz and blues with a curated dinner menu.",
    price: 2500,
    seats: 28,
  },
  {
    id: 2,
    title: "Chef's Table Experience",
    date: "Dec 20, 2026",
    time: "8:00 PM – 11:00 PM",
    desc: "An exclusive 14-seat dining experience hosted by Chef Arjun himself.",
    price: 4500,
    seats: 14,
  },
  {
    id: 3,
    title: "Wine & Dine Evening",
    date: "Jan 5, 2027",
    time: "7:30 PM – 10:30 PM",
    desc: "A curated wine-pairing journey with a 6-course gourmet menu.",
    price: 3500,
    seats: 24,
  },

  {
    id: 4,
    title: "Festive Dinner Celebration",
    date: "Jan 14, 2027",
    time: "7:00 PM – 11:00 PM",
    desc: "Celebrate the harvest season with a grand festive feast.",
    price: 2800,
    seats: 40,
  },
];

// ===== TESTIMONIALS =====
const testimonialsData = [
  {
    name: "Priya Sharma",
    role: "Food Critic",
    text: '"FoodieHub redefines fine dining in Bangalore. Every dish is a work of art, and the service is impeccable."',
    rating: 5,
    avatar: "P",
  },
  {
    name: "Rahul Mehta",
    role: "Regular Guest",
    text: '"The chef\'s tasting menu was an unforgettable journey. The flavors, the presentation, the ambiance — perfection."',
    rating: 5,
    avatar: "R",
  },
  {
    name: "Ananya Reddy",
    role: "Event Planner",
    text: '"We hosted our corporate dinner at FoodieHub, and it was flawless. The team went above and beyond."',
    rating: 5,
    avatar: "A",
  },
];

// ===== GALLERY =====
const galleryData = [
  { id: 1, category: "food", label: "Truffle Risotto" },
  { id: 2, category: "food", label: "Saffron Paneer" },
  { id: 3, category: "food", label: "Tandoori Salmon" },
  { id: 4, category: "interiors", label: "Dining Hall" },
  { id: 5, category: "interiors", label: "Bar Lounge" },
  { id: 6, category: "interiors", label: "Private Dining" },
  { id: 7, category: "chef", label: "Chef at Work" },
  { id: 8, category: "chef", label: "Plating Art" },
  { id: 9, category: "events", label: "Live Music" },
  { id: 10, category: "events", label: "Wine Tasting" },
  { id: 11, category: "food", label: "Chocolate Sphere" },
  { id: 12, category: "food", label: "Panna Cotta" },
];
